/**
    A page component that displays a blog form and sends the req.body off to
    a specified endpoint
      -  POST request to: /api/blog-entry/add
 */

import Head from "next/head";
import BlogForm from "../../components/blogForm/BlogForm";

import { useRouter } from "next/router";
import { Fragment } from "react";

import styles from "../../styles/Home.module.css";

function AddBlog() {

  // allows for the rerouting to home
  const router = useRouter();

  const addBlogHandler = async (data) => {
    try {
      // submit form
      const response = await fetch("/api/blog-entry/add", {
        method: "POST",
        // data needs to be sent as JSON
        body: JSON.stringify(data),
        headers: {
          "Content-Type": "application/json",
        },
      });

      const serverData = await response.json();
      console.log("serverData", serverData);

      // reload after response is successfully fetched
      router.reload();

    } catch {
      console.error(err);
      res.json({
        msg: "error with adding blog entry via addBlogHandler()",
      });
    }
  };

  return (
    <Fragment>
      <Head>
        <title>add-a-blog dynamic details!!!</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Add Blog</h1>
        <BlogForm addBlogHandler={addBlogHandler} />
      </main>
    </Fragment>
  );
}

export default AddBlog;
