//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//
//    @desc    add-blog with formik form, page component
//              - Formik forms for validation and UX
//              - submit a POST request to /api/blog-entry/add with the data that is contained in the Formik Form
//
//    @route   GET /register
//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

import Head from "next/head";
import BlogForm from "../../components/blogForm/BlogForm";

import { useRouter } from "next/router";
import { Fragment } from "react";

import styles from "../../styles/Home.module.css";

function AddBlog() {

  // Allows for the rerouting, reloading and redirecting of pages
  const router = useRouter();


  // SUBMIT FORM - post request to api
  const addBlogHandler = async (data) => {
    try {
      
      const response = await fetch("/api/blog-entry/add", {
        method: "POST",
        // data needs to be sent as JSON
        body: JSON.stringify(data),
        headers: {
          "Content-Type": "application/json",
        },
      });

      // reload after response is successfully fetched
      router.reload();

    } catch {
      console.error(err);
      res.json({
        msg: "error with adding blog entry with addBlogHandler()",
      });
    }
  };

  return (
    <Fragment>
      <Head>
        <title>add-a-blog dynamic details!!!</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Add Blog</h1>
        <BlogForm addBlogHandler={addBlogHandler} />
      </main>
    </Fragment>
  );
}

export default AddBlog;
