import Head from "next/head";
import Image from "next/image";

import styles from "../../../styles/Home.module.css";

import connectMongo from "../../../utils/connectMongo";

const BlogDetails = () => {
  return (
    <>
      <Head>
        <title>add-blog dynamic details!!!</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>

        <h1>blog details!!!</h1>

      </main>
    </>
  );
};
/**
  getStaticPaths()
    - this page is a dynamic page, and in order for next.js to prerender the contents of this page, 
      we need to inform it before hand the indivual path that the is page is expecting
    - this HAS to be in the pages folder
    - its going to tel next.js to statically prerender all paths and these paths are going to be specified here


 */

export async function getStaticPaths() {
  // connect to mongoDB
  const connectionString =
    "mongodb+srv://kp-ryanpilar:tBdotMyNQVZP84lc@cluster0.lvq17yt.mongodb.net/?retryWrites=true&w=majority";
  // const client = await MongoClient.connect(connectionString);
  const client = await connectMongo()

  const blogPostCollection = client.db().collection("posts");

  // lets return the path as to then tell next js to do its thing
  // find an empty object, and return its slug = 1, which means return only the id
  const blogPosts = await blogPostCollection.find({}, { slug: 1 }).toArray();
  client.close();
  // now, return the paths key which needs to be an array pf param objects
  // 'slug' needs to be the same as what you call it in your project
  return {
    paths: blogPosts.map(({ slug }) => ({
      params: { slug },
    })),
    // when any paths that are not returned in getstaticpaths, nextjs will automatically return a 404 page
    fallback: false,
  };
}

// in this page we hae dynamic route, and in order to do that we use:
export async function getStaticProps() {
  //  this page is a dynamic page, and in order for next.js to prerender
  //  the contents of this page, we need to inform it before hand the indivual path
}

export default BlogDetails;
